api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        formats:
            json: ['application/json']
        collection:
            pagination:
                enabled: false
    swagger:
        versions: [3]
    exception_to_status:
        Symfony\Component\Validator\Exception\ValidationFailedException: 422
